# Generated by Django 4.2.2 on 2024-06-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_knowledgebasemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebasemodel',
            options={},
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=10, verbose_name='文件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_content', models.TextField()),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_knowledge_base', to='app.knowledgebasemodel', verbose_name='所属知识库')),
            ],
            options={
                'db_table': 'tb_knowledge_base_file',
            },
        ),
    ]
