# Generated by Django 4.2.2 on 2024-06-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_knowledgebasemodel_options_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_chunk_content', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chunk', to='app.filemodel', verbose_name='所属文件')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_chunk_knowledge_base', to='app.knowledgebasemodel', verbose_name='所属知识库')),
            ],
            options={
                'db_table': 'tb_file_chunk',
                'ordering': ['create_time'],
            },
        ),
    ]
